### ISSUE TITLE
Question: What timespan does this cover?

### ISSUE THREAD

**Issue by Luc45** [geoffreywiseman/gh-actuse#11]
Does it show the total time consumed overall, or just a specific period of time, like the last 30 days, etc?

**Comment by Luc45** [comment]
Answering my own question, this repo uses this API: https://docs.github.com/en/rest/actions/workflows#get-workflow-usage

And it says:

> Gets the number of billable minutes used by a specific workflow **during the current billing cycle**.

Can we please add this information to the README?

**Comment by geoffreywiseman** [comment]
I'm working on a Go version of this (gh-actions-usage)[https://github.com/codiform/gh-actions-usage] using the new binary extension support, but I'll add it to the README for both projects.

**Comment by geoffreywiseman** [comment]
I'd love to be able to cover more than the current billing cycle or supply more information about the billing cycle, but the API's pretty limited on this topic so far.
