### ISSUE TITLE
Orgs with >100 Repos

### ISSUE THREAD

**Issue by geoffreywiseman** [geoffreywiseman/gh-actuse#3]
Right now I just ask for the most repos I can get in a single call, 100, and stop there. If you're looking at an organization with more repositories, some will be missing.

**Comment by SeanFromIT** [comment]
May not be the most efficient route, but I wrote a Python wrapper around your extension to compensate for this. 
[https://gist.github.com/SeanFromIT/83d5b429e613bbe1154dcdd1cd530623](https://gist.github.com/SeanFromIT/83d5b429e613bbe1154dcdd1cd530623)

**Comment by geoffreywiseman** [comment]
Ah -- so you have more than 100 repos that you need to handle, then? Ok, this one is probably pretty easy to address.

Yeah, wasn't too hard, so I fixed it -- feel free to get the latest and let me know if that works for you.

**Comment by geoffreywiseman** [comment]
If anyone has admin rights on an organization with only select repos enabled for GH Actions, that's something I don't have a good test case for right now, and I'd be happy to know that that works, particularly for >100 repos.

**Comment by geoffreywiseman** [comment]
On the only org I currently have admin rights on, the output says:
"- GitHub Actions enabled on All Repos"

If it's enabled on selected repos, it *should* say:
"- GitHub Actions enabled on Selected Repos"

And then go on to do its work only on those repos. I will look at setting up a test Organization sometime. ;)
